parsers:
- crowdsecurity/syslog-logs
- crowdsecurity/dateparse-enrich
- ./parsers/s01-parse/crowdsecurity/synology-dsm-logs.yaml
scenarios:
- ./scenarios/crowdsecurity/synology-dsm-bf-slow-1h.yaml
postoverflows:
- ""
log_file: synology-dsm-logs-bf-slow.log
log_type: syslog
labels: { }
ignore_parsers: false

